version: '3.8'

services:
  stock-predictor:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - TZ=Asia/Taipei
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    ports:
      - "8501:8501"  # For future web interface if needed
    restart: unless-stopped
